virtualeconomy/js-vsys

spec/contract_spec/v_option_ctrt_spec.js
src/contract/v_option_ctrt.js
src/index.js

add v option ctrt.
under development.

feat: add v option ctrt

---

src/contract/v_option_ctrt.js
src/model.js

fix v option and model.
tested manually.

fix: v option and model

---

src/contract/v_option_ctrt.js

fix: change getters in v option to work properly

---

doc/smart_contract/tok_ctrt_no_split.md
doc/smart_contract/tok_ctrt_split.md
doc/smart_contract/tok_ctrt_v2.md
doc/smart_contract/v_escrow_ctrt.md

docs: add token contract docs

---

doc/smartContract/atomicSwapCtrt.md
docs/nfr_ctrt_v2.md
docs/nft_ctrt.md

docs: add nft ctrt

---

src/account.js
src/api.js
src/chain.js
src/model.js

complete non ctrt functions
tested on http://veldidina.vos.systems:9928/

feat: complete non ctrt functions

---

doc/smart_contract/v_option_ctrt.md

Add V Option docs
No tests required

docs: add v option contract docs

---

doc/smart_contract/v_escrow_ctrt.md

Add docs for V Escrow contract.
No need for testing.

docs: add v escrow contract

---

doc/smart_contract/atomic_swap_ctrt.md
doc/smart_contract/atomic_swap_helper.md

add atomic swap ctrt docs.
no need to test.

docs: add atomic swap ctrt docs

---

doc/smart_contract/atomic_swap_ctrt.md
spec/contract_spec/atomic_swap_ctrt_spec.js
src/contract/atomic_swap_ctrt.js
src/contract/atomic_swap_helper.js

update atomic swap ctrt.
tested with Jasmine.

fix: update atomic swap ctrt

---

doc/smart_contract/nft_ctrt.md
doc/smart_contract/nft_ctrt_v2.md

docs: add nft ctrt, nft ctrt v2

---

doc/smart_contract/v_stable_swap_ctrt.md
doc/smart_contract/v_swap_ctrt.md

docs: add v stable swap ctrt & v swap ctrt

---

doc/smart_contract/sys_ctrt.md

docs: create sys ctrt

---

doc/smart_contract/pay_chan_ctrt.md

docs: create pay chan ctrt

---

doc/chain.md
doc/smart_contract/nft_ctrt.md
doc/smart_contract/nft_ctrt_v2.md
doc/smart_contract/pay_chan_ctrt.md
doc/smart_contract/sys_ctrt.md
doc/smart_contract/v_option_ctrt.md
doc/smart_contract/v_stable_swap_ctrt.md
doc/smart_contract/v_swap_ctrt.md
doc/wallet.md
src/chain.js

remove default network
tested manually.

Refactor: remove default network

---

spec/helpers/spec_helper.js

add ChainID in spec helper.
tested by jasmine.

fix: add ChainID

---

src/model.js

fixed chainId not being able to test the equivalence

fix: fixed chainID mismatch even though it is

---

.npmignore
README.md
doc/smart_contract/atomic_swap_ctrt.md
doc/smart_contract/atomic_swap_helper.md
doc/smart_contract/lock_ctrt.md
doc/smart_contract/nft_ctrt.md
doc/smart_contract/nft_ctrt_v2.md
doc/smart_contract/pay_chan_ctrt.md
doc/smart_contract/sys_ctrt.md
doc/smart_contract/tok_ctrt_no_split.md
doc/smart_contract/tok_ctrt_split.md
doc/smart_contract/tok_ctrt_v2.md
doc/smart_contract/v_escrow_ctrt.md
doc/smart_contract/v_option_ctrt.md
doc/smart_contract/v_stable_swap_ctrt.md
doc/smart_contract/v_swap_ctrt.md
package.json

Prepare repo to publish npm package. Update docs to reflect import using node modules.
`0.1.1-alpha` has been pushed to npm and tested successfully.

build: npmpublish

---

.npmignore
README.md
doc/smart_contract/atomic_swap_ctrt.md
doc/smart_contract/atomic_swap_helper.md
doc/smart_contract/lock_ctrt.md
doc/smart_contract/nft_ctrt.md
doc/smart_contract/nft_ctrt_v2.md
doc/smart_contract/pay_chan_ctrt.md
doc/smart_contract/sys_ctrt.md
doc/smart_contract/tok_ctrt_no_split.md
doc/smart_contract/tok_ctrt_split.md
doc/smart_contract/tok_ctrt_v2.md
doc/smart_contract/v_escrow_ctrt.md
doc/smart_contract/v_option_ctrt.md
doc/smart_contract/v_stable_swap_ctrt.md
doc/smart_contract/v_swap_ctrt.md
package.json

release: v0.1.1

---

spec/contract_spec/v_option_ctrt_spec.js

Minor comment fix.
No need for testing.

test: fixed typo in comments

---

src/account.js

update lease docstring.
no need to test.

fix: update lease docstring

---

src/api.js

Add transaction api which returns transaction records.
Test manually.

feat: add tx list api

---

README.md

Fix comments in the example codes.
No tests are required.

docs: fix comments in example code

---

src/account.js

Fix method getTokBal of class Account.
Tested locally.

fix: fix method getTokBal in class Account

---

src/contract/tok_ctrt_factory.js
src/model.js

1. Add function to get tokIdx from tokId.
2. Add export to TokCtrtType type.
Tested locally.

feat: get tokIdx from tokId

---

src/data_entry.js
src/utils/big_number.js
src/utils/bytes_packer.js

Fixes bug related to export and bignum.
All local tests successfully passed.

fix: bignumbug

---

package-lock.json
package.json

release: 0.2.5
no need to test.

release: 0.2.5

---

src/tx_req.js

1. Remove jasmine import
All changes have been tested locally.

fix: remove import jasmine

---

package-lock.json
package.json

Merge changes of release v0.1.4 to branch main

release: v0.2.6

---

src/model.js

Merge changes of release v0.2.6 to branch main.
Functional tests passed locally.

release: 0.2.6

---

src/api.js

Reverts virtualeconomy/js-vsys#97

Revert "fix: fetch polyfill for node<18"

---

src/api.js

fix: global -> globalThis

---

src/contract/sys_ctrt.js

added generateTxID into sys_ctrt.js

added generateTxID function

---

package.json

release: 0.2.7
